spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
    livereload:
      enabled: true
